version: '3'

services:
  pgsql:
    image: postgres
    container_name: db-apps
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=joni
      - POSTGRES_PASSWORD=joni
      - POSTGRES_DB=gpromin
    ports:
      - '5433:5432'
    restart: always

  php:
    build: ./dockerfiles
    container_name: php-apps
    volumes:
      - "./src:/var/www/src"
      - "./dockerfiles/config/php/php-fpm.conf:/etc/php-fpm.conf"
      - "./dockerfiles/config/php/www.conf:/etc/php-fpm.d/www.conf"
      - "./dockerfiles/config/php/php.ini:/usr/local/etc/php/php.ini"
    depends_on:
      - pgsql

  nginx:
    image: nginx:latest
    container_name: web-apps
    depends_on:
      - php
    volumes:
      - "./src:/var/www/src"
      - "./dockerfiles/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    restart: always